[custom.all.tpl]
type   = "local"
path   = "."
ipkg   = "tpl.ipkg"
test   = "test/test.ipkg"

[custom.all]
ilex-debug.commit   = "latest:main"
ilex-core.commit    = "latest:main"
ilex.commit         = "latest:main"
ilex-streams.commit = "latest:main"
